---
# These tasks install the UMD4 repo

# Always best to install yum-priorities with UMD4
- name: Install yum-priorities plugin
  yum: name=yum-priorities state=present

# Install UMD4 repo
- name: Install UMD4 repo
  yum: name=http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/base/umd-release-4.0.0-1.el7.noarch.rpm state=present

# Import UMD4 gpg key
- name: Import UMD4 gpg key
  rpm_key: >
    state=present
    key=http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY